container:
  image: node:latest

check_task:
  environment:
    MONGO_URL: ENCRYPTED[51f3c8f4f0235142bc2efca6848fd09c595694be1f1b29ea80489f8abb91f394b8f8a400cdaf1545f869e1d8a7dfeb38]
    NODE_ENV: DEV
    API_PREFIX: v1
    JWT_SECRET: ENCRYPTED[72316783ca4e8b7ce79d0776cd95edc7b560ac48825f5e48add51afb936ebc944330f07f32f91c6c02576be430e5b11b]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  test_script: npm test
