version: "3.3"

services:
  mongo:
    container_name: twitter-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
    network_mode: bridge

  twitter:
    container_name: twitter-backend
    image: twitter-backend
    volumes:
      - .:/usr/src/app
    build: .
    ports:
      - "3000:3000"
    network_mode: bridge
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/twitter-backend --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
    links:
      - mongo
    environment:
      NODE_ENV: DEV
      API_PREFIX: v1
      MONGO_URL: mongodb://mongo/twitter-backend
      JWT_SECRET: test
    restart: always
