version: '3.3'

services:

  mongo:
    container_name: twitter-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always
    networks: 
      - backend
      
      
  twitter:
    container_name: twitter-backend
    image: twitter-backend
    volumes:
      - .:/usr/src/app
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      NODE_ENV: DEV
      API_PREFIX: v1
      MONGO_URL: mongodb://mongo/twitter-backend
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"