version: '3.3'

services:

  mongo:
    container_name: twitter-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks: 
      - backend
      
      
  twitter:
    container_name: twitter-backend
    image: alpine
    build: .
    ports:
    - '3000:3000'
    restart: always
    links:
      - mongo
    environment:
      NODE_ENV: DEV
      API_PREFIX: v1
      MONGO_URL: mongodb://mongo:27017/twitter-backend
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"